services:
  - type: web
    name: technest-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://technest-frontend.onrender.com

  - type: web
    name: technest-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
