services:
  - type: web
    name: technest-api
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
